- hosts: maseeh
  remote_user: kxiong22
  environment:
    PATH: /home/kxiong22/.nvm/versions/node/v14.2.0/bin:{{ ansible_env.PATH }}
  tasks:
    - name: get latest version from github
      git:
        repo: ssh://git@github.com/maseeh-webtech/maseeh-desk.git
        version: main
        dest: /srv/maseeh-desk
      notify:
        - update dependencies
        - rebuild client
        - restart server
        - update crontab

  handlers:
    - name: update dependencies
      yarn:
        path: /srv/maseeh-desk

    - name: rebuild client
      command: yarn build:client
      args:
        chdir: /srv/maseeh-desk

    - name: restart server
      shell: "pm2 delete maseeh-desk; pm2 start --name maseeh-desk server.js"
      args:
        chdir: /srv/maseeh-desk/server

    - name: update crontab
      cron:
        minute: "0"
        hour: "17"
        job: /home/kxiong22/.nvm/versions/node/v14.2.0/bin/node /srv/maseeh-desk/server/library-reminder.js > /tmp/library-reminder.log 2>&1
